// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func Add(x2 Audio, x22 Audio) (x Audio) {
	var v Audio
	var v2 Audio
	var v3 Audio
	var v4 Audio
	var v5 int
	v2 = x2
	v3 = x2
	v4 = x22
	x222 := len(v2)
	v5 = x222
	x3 := make(Audio, v5)
	v = x3
	x4 := v.Add(v3, v4)
	x = x4
	return
}
