// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *AttackReleaseEnv) Attack() () {
	var v *AttackReleaseEnv
	var v2 *bool
	var v3 bool
	v = x
	x2 := &v.release
	v2 = x2
	const x3 = false
	v3 = x3
	*v2 = v3
	return
}
