// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x *AttackReleaseEnv) SetReleaseTime(x2 float64) () {
	var v *AttackReleaseEnv
	var v2 float64
	var v3 float64
	var v4 float64
	var v5 float64
	var v6 bool
	var v7 *AttackReleaseEnv
	var v8 *AttackReleaseEnv
	var v9 *Params
	var v10 float64
	var v11 float64
	v = x//env
	v7 = x//env
	v8 = x//env
	v2 = x2
	v3 = x2
	x22 := &v7.Params
	v9 = x22
	x3 := &v9.SampleRate
	v4 = *x3
	x4 := v4 * v3
	v10 = x4
	v5 = x4
	var v12 float64
	x5 := v10 != v12
	v6 = x5
	if v6 {
		var v13 float64
		var v14 float64
		var v15 float64
		const x6 = 0.1
		v13 = x6
		const x7 = 1
		v14 = x7
		x8 := v14 / v5
		v15 = x8
		x9 := math.Pow(v13, v15)
		v11 = x9
	}
	v8.down = v11
	v.releaseTime = v2
}
