// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *AttackReleaseEnv) SetAudioParams(params Params) () {
	var v *AttackReleaseEnv
	var v2 Params
	var v3 *AttackReleaseEnv
	var v4 *AttackReleaseEnv
	var v5 *AttackReleaseEnv
	var v6 *Params
	var v7 *AttackReleaseEnv
	var v8 Params
	var v9 *Audio
	var v10 float64
	var v11 *AttackReleaseEnv
	var v12 float64
	v4 = x//e
	v7 = x//e
	v = x//e
	v11 = x//e
	v5 = x//e
	v2 = params
	v8 = params
	v3 = x//e
	x2 := &v.Out
	v9 = x2
	v9.SetAudioParams(v2)
	x3 := &v4.Params
	v6 = x3
	*v6 = v8//;0
	x4 := &v11.releaseTime
	v10 = *x4
	v5.SetReleaseTime(v10)//0;
	x5 := &v3.attackTime
	v12 = *x5
	v7.SetAttackTime(v12)//0;
}
