// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

type AttackReleaseEnv struct{Params Params; attackTime float64; releaseTime float64; up float64; down float64; release bool; x float64; Out Audio}