// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x *AttackReleaseEnv) SetAttackTime(x2 float64) () {
	var v float64
	var v2 *float64
	var v3 *AttackReleaseEnv
	var v4 *AttackReleaseEnv
	var v5 float64
	var v6 *AttackReleaseEnv
	var v7 float64
	var v8 float64
	var v9 float64
	var v10 bool
	var v11 *float64
	var v12 *Params
	var v13 float64
	v4 = x//env
	v7 = x2
	v = x2
	v3 = x//env
	v6 = x//env
	x22 := &v4.up
	v2 = x22
	x3 := &v6.Params
	v12 = x3
	x4 := &v12.SampleRate
	v13 = *x4
	x5 := v13 * v7
	v8 = x5
	v9 = x5
	var v14 float64
	x6 := v9 != v14
	v10 = x6
	if v10 {
		var v15 float64
		var v16 float64
		var v17 float64
		const x7 = 0.1
		v17 = x7
		const x8 = 1
		v15 = x8
		x9 := v15 / v8
		v16 = x9
		x10 := math.Pow(v17, v16)
		v5 = x10
	} else  {
		const x11 = 1
		v5 = x11
	}
	*v2 = v5
	x12 := &v3.attackTime
	v11 = x12
	*v11 = v
}
