// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x Audio) Zero() () {
	var v Audio
	v = x
	for i := range v {
		var v2 = &v[i]
		var v3 *float64
		v3 = v2
		var v4 float64
		*v3 = v4
	}
}
