// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x Audio) MulX(x2 float64) (x3 Audio) {
	var v Audio
	var v2 float64
	v2 = x2
	v = x
	x3 = x
	for i := range v {
		var v3 = &v[i]
		var v4 float64
		var v5 *float64
		var v6 float64
		v5 = v3
		v4 = *v3
		x22 := v4 * v2
		v6 = x22
		*v5 = v6
	}
	return
}
