// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x2 Audio) Add(x3 Audio, x4 Audio) (x Audio) {
	var v Audio
	var v2 Audio
	var v3 Audio
	v = x2
	x = x2
	v2 = x3
	v3 = x4
	for k := range v {
		var v4 = &v[k]
		var v5 *float64
		var v6 float64
		var v7 float64
		var v8 float64
		var v9 int
		var v10 int
		v10 = k
		v5 = v4
		v9 = k
		x22 := &v2[v9]
		v6 = *x22
		x32 := &v3[v10]
		v7 = *x32
		x42 := v6 + v7
		v8 = x42
		*v5 = v8
	}
	return
}
