// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *Audio) SetAudioParams(p Params) () {
	var v Params
	var v2 int
	var v3 Audio
	var v4 *Audio
	v4 = x
	v = p
	x2 := v.BufferSize
	v2 = x2
	x3 := make(Audio, v2)
	v3 = x3
	*v4 = v3
}
