// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x Audio) Mul(x2 Audio, x3 Audio) (x4 Audio) {
	var v Audio
	var v2 Audio
	var v3 Audio
	v3 = x3
	v = x
	x4 = x
	v2 = x2
	for k := range v {
		var v4 = &v[k]
		var v5 int
		var v6 *float64
		var v7 float64
		var v8 float64
		var v9 float64
		var v10 int
		v10 = k
		v5 = k
		v6 = v4
		x22 := &v2[v10]
		v7 = *x22
		x32 := &v3[v5]
		v8 = *x32
		x42 := v7 * v8
		v9 = x42
		*v6 = v9
	}
	return
}
