// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x Audio) Tanh(x2 Audio) (x3 Audio) {
	var v Audio
	var v2 Audio
	v2 = x2
	v = x
	x3 = x
	for k := range v2 {
		var v3 = &v2[k]
		var v4 int
		var v5 float64
		var v6 *float64
		var v7 float64
		v5 = *v3
		v4 = k
		x22 := &v[v4]
		v6 = x22
		x32 := math.Tanh(v5)
		v7 = x32
		*v6 = v7
	}
	return
}
