// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *Beat) Beat() () {
	var v int
	var v2 int
	var v3 *Beat
	var v4 *int
	var v5 int
	var v6 int
	var v7 *Beat
	var v8 *Beat
	var v9 int
	var v10 bool
	var v11 int
	var v12 *Beat
	var v13 int
	var v14 *Params
	v8 = x
	v3 = x
	v7 = x
	v12 = x
	x2 := &v3.i
	v11 = *x2
	v4 = x2
	v5 = *x2
	v6 = *x2
	v13 = *x2
	x3 := &v7.Params
	v14 = x3
	x4 := &v14.BufferSize
	v9 = *x4
	v = *x4
	x5 := v5 < v9
	v10 = x5
	if v10 {
		var v15 func(offset int)
		var v16 int
		x6 := &v8.f
		v15 = *x6
		v15(v13)
		x7 := &v12.n
		v16 = *x7
		x8 := v6 + v16
		v11 = x8
	}
	x9 := v11 - v
	v2 = x9
	*v4 = v2
	return
}
