// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *ControlLine) SetAudioParams(p Params) () {
	var v *ControlLine
	var v2 float64
	var v3 float64
	var v4 Params
	var v5 *ControlLine
	var v6 *ControlLine
	var v7 *ControlLine
	var v8 float64
	var v9 float64
	var v10 float64
	var v11 float64
	var v12 *ControlLine
	var v13 float64
	var v14 float64
	v4 = p
	v5 = x
	v6 = x
	v = x
	v7 = x
	v12 = x
	x2 := &v.Value2
	v13 = *x2
	x3 := &v6.Value1
	v2 = *x3
	v8 = *x3
	x4 := v13 - v8
	v9 = x4
	x5 := &v7.Duration_
	v10 = *x5
	x6 := v9 / v10
	v11 = x6
	x7 := v4.SampleRate
	v14 = x7
	x8 := v11 / v14
	v3 = x8
	v12.step = v3
	v5.x = v2
	return
}
