// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

type Control struct{Params Params; Periods []ControlPeriod; elapsed []float64; i int; t float64; Out Audio}