// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *ControlLine) Duration() (d float64) {
	var v *ControlLine
	v = x
	x2 := &v.Duration_
	d = *x2
	return
}
