// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

type ControlExp struct{Duration_ float64; Value1 float64; Value2 float64; x float64; a float64}