// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *ControlExp) Control(a Audio) () {
	var v float64
	var v2 float64
	var v3 float64
	var v4 *ControlExp
	var v5 *ControlExp
	var v6 float64
	var v7 *ControlExp
	var v8 Audio
	var v9 float64
	var v10 float64
	var v11 *float64
	v4 = x
	v7 = x
	v5 = x
	v8 = a
	x2 := &v4.x
	v9 = *x2
	v6 = *x2
	v11 = x2
	v3 = *x2
	x3 := &v7.Value2
	v = *x3
	x4 := &v5.a
	v10 = *x4
	for i := range v8 {
		var v12 = &v8[i]
		var v13 *float64
		var v14 float64
		var v15 float64
		v13 = v12
		x5 := v - v3
		v14 = x5
		x6 := v14 * v10
		v15 = x6
		*v13 = v9
		x7 := v6 + v15
		v6 = x7
		v9 = x7
		v3 = x7
		v2 = x7
	}
	*v11 = v2
	return
}
