// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x *ControlExp) SetAudioParams(p Params) () {
	var v float64
	var v2 float64
	var v3 *ControlExp
	var v4 float64
	var v5 Params
	var v6 float64
	var v7 float64
	var v8 *ControlExp
	var v9 float64
	var v10 float64
	var v11 float64
	var v12 float64
	var v13 float64
	var v14 *ControlExp
	var v15 *ControlExp
	v3 = x
	v14 = x
	v8 = x
	v15 = x
	v5 = p
	x2 := &v3.Value1
	v9 = *x2
	v15.x = v9
	const x3 = 1
	v10 = x3
	v12 = x3
	const x4 = 0.01
	v7 = x4
	x5 := &v14.Duration_
	v11 = *x5
	x6 := v5.SampleRate
	v4 = x6
	x7 := v11 * v4
	v = x7
	x8 := v10 / v
	v6 = x8
	x9 := math.Pow(v7, v6)
	v13 = x9
	x10 := v12 - v13
	v2 = x10
	v8.a = v2
	return
}
