// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *ControlExp) Duration() (d float64) {
	var v *ControlExp
	v = x
	x2 := &v.Duration_
	d = *x2
	return
}
