package audio

import (
	"code.google.com/p/gordon-go/gui"
)

var KeyPitch = map[int]float64{
	gui.KeyZ: -12,
	gui.KeyS: -11,
	gui.KeyX: -10,
	gui.KeyD: -9,
	gui.KeyC: -8,
	gui.KeyV: -7,
	gui.KeyG: -6,
	gui.KeyB: -5,
	gui.KeyH: -4,
	gui.KeyN: -3,
	gui.KeyJ: -2,
	gui.KeyM: -1,
	gui.KeyComma: 0,
	gui.KeyL: 1,
	gui.KeyPeriod: 2,
	gui.KeySemicolon: 3,
	gui.KeySlash: 4,
	gui.KeyQ: 0,
	gui.Key2: 1,
	gui.KeyW: 2,
	gui.Key3: 3,
	gui.KeyE: 4,
	gui.KeyR: 5,
	gui.Key5: 6,
	gui.KeyT: 7,
	gui.Key6: 8,
	gui.KeyY: 9,
	gui.Key7: 10,
	gui.KeyU: 11,
	gui.KeyI: 12,
	gui.Key9: 13,
	gui.KeyO: 14,
	gui.Key0: 15,
	gui.KeyP: 16,
	gui.KeyLeftBracket: 17,
	gui.KeyEqual: 18,
	gui.KeyRightBracket: 19,
	gui.KeyBackslash: 21,
}
