// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x2 *Line) LineRate(rate float64) (x Audio) {
	var v *Line
	var v2 *Params
	var v3 float64
	var v4 *Line
	var v5 *Line
	var v6 float64
	var v7 Audio
	var v8 float64
	v4 = x2
	v = x2
	v5 = x2
	v6 = rate
	x22 := &v4.Out
	v7 = *x22
	x = *x22
	x3 := &v.Params
	v2 = x3
	x4 := &v2.SampleRate
	v3 = *x4
	x5 := v6 / v3
	v8 = x5
	for i := range v7 {
		var v9 = &v7[i]
		var v10 *float64
		var v11 float64
		var v12 *float64
		var v13 float64
		var v14 float64
		v10 = v9
		x6 := &v5.x
		v11 = *x6
		v12 = x6
		x7 := v11 + v8
		v13 = x7
		v14 = x7
		*v10 = v13
		*v12 = v14
	}
	return
}
