// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func MakeAttackReleaseEnv(attackTime float64, releaseTime float64) (x AttackReleaseEnv) {
	var v float64
	var v2 float64
	v2 = attackTime
	v = releaseTime
	x2 := AttackReleaseEnv{attackTime: v2, releaseTime: v}
	x = x2
	return
}
