// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func min(x int, y int) (x2 int) {
	var v int
	var v2 int
	var v3 bool
	var v4 int
	x2 = y
	v4 = x
	v = x
	v2 = y
	x3 := v4 < v2
	v3 = x3
	if v3 {
		var v5 int
		x4 := v + v5
		x2 = x4
	}
	return
}
