// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func Mul(x2 Audio, x22 Audio) (x Audio) {
	var v Audio
	var v2 Audio
	var v3 Audio
	var v4 int
	var v5 Audio
	v = x2
	v2 = x2
	v3 = x22
	x222 := len(v)
	v4 = x222
	x3 := make(Audio, v4)
	v5 = x3
	x = x3
	for k := range v5 {
		var v6 = &v5[k]
		var v7 int
		var v8 int
		var v9 *float64
		var v10 float64
		var v11 float64
		var v12 float64
		v9 = v6
		v7 = k
		v8 = k
		x4 := &v2[v7]
		v10 = *x4
		x5 := &v3[v8]
		v11 = *x5
		x6 := v10 * v11
		v12 = x6
		*v9 = v12
	}
	return
}
