// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"sync"
)

func (x *MultiVoice) StartVoice(v Voice) () {
	var v2 Voice
	var v3 Params
	var v4 *sync.Mutex
	var v5 *MultiVoice
	var v6 map[Voice]struct{}
	var v7 *sync.Mutex
	var v8 *MultiVoice
	var v9 *MultiVoice
	var v10 interface{}
	v2 = v
	v8 = x
	v9 = x
	v5 = x
	v10 = v
	x2 := &v9.voices
	v6 = *x2
	x3 := &v5.Params
	v3 = *x3
	v3.Set(v10)//;0
	x4 := &v8.mu
	v7 = x4
	v4 = x4
	v7.Lock()//0;1
	var v11 struct{}
	v6[v2] = v11//1;2
	v4.Unlock()//2;
}
