// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"sync"
)

func (x *MultiVoice) StopVoice(v Voice) () {
	var v2 *MultiVoice
	var v3 Voice
	var v4 map[Voice]struct{}
	var v5 *sync.Mutex
	var v6 *sync.Mutex
	var v7 *MultiVoice
	v7 = x
	v2 = x
	v3 = v
	x2 := &v2.voices
	v4 = *x2
	x3 := &v7.mu
	v5 = x3
	v6 = x3
	v5.Lock()//;0
	delete(v4, v3)//0;1
	v6.Unlock()//1;
}
