// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"sync"
)

func (x2 *MultiVoice) Sing() (x Audio, done bool) {
	var v Audio
	var v2 map[Voice]struct{}
	var v3 *MultiVoice
	var v4 *MultiVoice
	var v5 Audio
	var v6 Audio
	var v7 *sync.Mutex
	var v8 *MultiVoice
	var v9 *sync.Mutex
	var v10 map[Voice]struct{}
	var v11 map[Voice]struct{}
	var v12 int
	v8 = x2
	v3 = x2
	v4 = x2
	x22 := &v8.Out
	x = *x22
	v5 = *x22
	v6 = *x22
	v = *x22
	x3 := &v4.voices
	v10 = *x3
	v2 = *x3
	v11 = *x3
	x4 := len(v10)
	v12 = x4
	var v13 int
	x5 := v12 == v13
	done = x5
	v5.Zero()//;0
	x6 := &v3.mu
	v7 = x6
	v9 = x6
	v7.Lock()//;1
	for k := range v11 {
		var v14 Voice
		var v15 Audio
		var v16 bool
		var v17 Voice
		v17 = k
		v14 = k
		x7, done2 := v14.Sing()
		v15 = x7
		v16 = done2
		v6.Add(v, v15)
		if v16 {
			delete(v2, v17)
		}
	}//0,1;2
	v9.Unlock()//2;
	return
}
