// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func NewControl(x []ControlPeriod) (c Control) {
	var v []ControlPeriod
	var v2 []ControlPeriod
	var v3 int
	var v4 []float64
	var v5 []float64
	var v6 float64
	var v7 []ControlPeriod
	v2 = x
	v7 = x
	v = x
	x2 := len(v)
	v3 = x2
	x3 := make([]float64, v3)
	v4 = x3
	v5 = x3
	for k := range v7 {
		var v8 = &v7[k]
		var v9 float64
		var v10 float64
		var v11 int
		var v12 ControlPeriod
		v11 = k
		v12 = *v8
		x4 := v12.Duration()
		v9 = x4
		x5 := v9 + v6
		v10 = x5
		v6 = x5
		v5[v11] = v10
	}
	x6 := Control{Periods: v2, elapsed: v4}
	c = x6
	return
}
