// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func NewMultiVoice() (x *MultiVoice) {
	var v map[Voice]struct{}
	var v2 int
	x2 := make(map[Voice]struct{}, v2)
	v = x2
	x3 := &MultiVoice{voices: v}
	x = x3
	return
}
