// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func NewPattern(x2 []Note, x Instrument) (x22 *Pattern) {
	var v []Note
	var v2 Instrument
	v = x2
	v2 = x
	x222 := &Pattern{Notes: v, Instrument: v2}
	x22 = x222
	return
}
