// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func NewPolyphonicInstrument(x func(_ Note) Voice) (i Instrument) {
	var v func(_ Note) Voice
	var v2 *MultiVoice
	v = x
	x2 := NewMultiVoice()
	v2 = x2
	x3 := &PolyphonicInstrument{MultiVoice: v2, newVoice: v}
	i = x3
	return
}
