// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func NewSineBeat(amp float64, sineFreq float64, beatFreq float64, beatWidth float64) (x *SineBeat) {
	var v float64
	var v2 float64
	var v3 float64
	var v4 float64
	v3 = beatFreq
	v4 = beatWidth
	v = amp
	v2 = sineFreq
	x2 := &SineBeat{amp: v, sineFreq: v2, beatFreq: v3, beatWidth: v4}
	x = x2
	return
}
