// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x *NormalOsc) Osc(freq float64, width float64) (x2 Audio) {
	var v float64
	var v2 float64
	var v3 float64
	var v4 *NormalOsc
	var v5 float64
	var v6 *SineOsc
	var v7 float64
	var v8 Audio
	v4 = x
	v5 = freq
	v = width
	x22 := &v4.Sine
	v6 = x22
	const x3 = 2
	v2 = x3
	x4 := v5 / v2
	v7 = x4
	x5 := v6.SineFreq(v7)
	v8 = x5
	x2 = x5
	x6 := math.Log(v)
	v3 = x6
	for i := range v8 {
		var v9 = &v8[i]
		var v10 float64
		var v11 float64
		var v12 *float64
		var v13 float64
		var v14 float64
		var v15 float64
		var v16 float64
		v12 = v9
		v11 = *v9
		x7 := v11 * v3
		v13 = x7
		v14 = x7
		x8 := v13 * v14
		v15 = x8
		var v17 float64
		x9 := v17 - v15
		v16 = x9
		x10 := math.Exp(v16)
		v10 = x10
		*v12 = v10
	}
	return
}
