// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

type Pattern struct{Params Params; Notes []Note; i int; t float64; Instrument Instrument}