// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x2 *Pattern) Sing() (x Audio, done bool) {
	var v *Pattern
	var v2 float64
	var v3 int
	var v4 int
	var v5 *Pattern
	var v6 *Pattern
	var v7 *Params
	var v8 *Pattern
	var v9 int
	var v10 []Note
	var v11 float64
	var v12 float64
	var v13 *int
	var v14 []Note
	var v15 bool
	var v16 *Params
	var v17 float64
	var v18 float64
	var v19 bool
	var v20 *Pattern
	var v21 *Pattern
	var v22 *float64
	var v23 float64
	var v24 Instrument
	v5 = x2//p
	v8 = x2//p
	v20 = x2//p
	v = x2//p
	v6 = x2//p
	v21 = x2//p
	x22 := &v6.t
	v22 = x22
	v11 = *x22
	x3 := &v8.Params
	v16 = x3
	v7 = x3
	x4 := &v16.BufferSize
	v9 = *x4
	x5 := (float64)(v9)
	v23 = x5
	x6 := &v7.SampleRate
	v12 = *x6
	x7 := v23 / v12
	v17 = x7
	x8 := v11 + v17
	v18 = x8
	v2 = x8//t1
	*v22 = v18
	x9 := &v.Notes
	v14 = *x9
	v10 = *x9
	x10 := &v20.i
	v4 = *x10
	v13 = x10
	for k := 0;; k++ {
		var v25 int
		var v26 int
		var v27 int
		var v28 Note
		var v29 bool
		var v30 int
		var v31 bool
		var v32 *Note
		var v33 float64
		var v34 Instrument
		v25 = k
		x11 := v25 + v4
		v26 = x11
		v3 = x11
		v30 = x11
		x12 := len(v14)
		v27 = x12
		x13 := v30 >= v27
		v31 = x13
		if v31 {
			const x14 = true//;0
			v19 = x14
			break//0;
		}//;1
		x15 := &v10[v26]//1;
		v28 = *x15
		v32 = x15
		x16 := &v32.Start
		v33 = *x16
		x17 := v33 >= v2
		v29 = x17
		if v29 {
			break
		}//;2
		x18 := &v21.Instrument
		v34 = *x18
		v34.Play(v28)//2;
	}//;3
	x19 := &v5.Instrument
	v24 = *x19
	x20, done2 := v24.Sing()//3;
	x = x20
	v15 = done2
	x21 := v15 && v19
	done = x21
	*v13 = v3
	return
}
