// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func PitchToFreq(pitch float64) (freq float64) {
	var v float64
	var v2 float64
	var v3 float64
	var v4 float64
	var v5 float64
	var v6 float64
	v = pitch
	const x = 2
	v2 = x
	const x2 = 12
	v3 = x2
	x3 := v / v3
	v4 = x3
	x4 := math.Pow(v2, v4)
	v5 = x4
	const x5 = 512
	v6 = x5
	x6 := v5 * v6
	freq = x6
	return
}
