// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func (x *SineBeats) Sing() (x2 Audio) {
	var v []*SineBeat
	var v2 *SineBeats
	var v3 *SineBeats
	var v4 Audio
	var v5 Audio
	var v6 Audio
	v2 = x
	v3 = x
	x22 := &v2.Out
	v4 = *x22
	v5 = *x22
	v6 = *x22
	x2 = *x22
	v4.Zero()//;0
	x3 := &v3.Beats//0;
	v = *x3
	for i := range v {
		var v7 = &v[i]
		var v8 *SineBeat
		var v9 Audio
		v8 = *v7
		x23 := v8.Sing()
		v9 = x23
		v5.Add(v6, v9)
	}
	return
}
