// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func (x2 *SineOsc) SineFreq(freq float64) (x Audio) {
	var v float64
	var v2 *Params
	var v3 float64
	var v4 float64
	var v5 *SineOsc
	var v6 *SineOsc
	var v7 float64
	var v8 float64
	var v9 float64
	var v10 float64
	var v11 *SineOsc
	var v12 Audio
	v5 = x2
	v11 = x2
	v6 = x2
	v = freq
	x22 := &v5.Out
	v12 = *x22
	x = *x22
	x3 := &v11.Params
	v2 = x3
	x4 := &v2.SampleRate
	v3 = *x4
	x5 := v / v3
	v7 = x5
	const x6 = 2
	v4 = x6
	x7 := v7 * v4
	v8 = x7
	const x8 = math.Pi
	v9 = x8
	x9 := v8 * v9
	v10 = x9
	for i := range v12 {
		var v13 = &v12[i]
		var v14 *float64
		var v15 float64
		var v16 *float64
		var v17 float64
		var v18 float64
		var v19 float64
		v14 = v13
		x10 := &v6.phase
		v15 = *x10
		v16 = x10
		x11 := v15 + v10
		v17 = x11
		v18 = x11
		*v16 = v17
		x12 := math.Sin(v18)
		v19 = x12
		*v14 = v19
	}
	return
}
