// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

func Sub(x2 Audio, x3 Audio) (x Audio) {
	var v Audio
	var v2 int
	var v3 Audio
	var v4 Audio
	var v5 Audio
	v4 = x2
	v5 = x2
	v = x3
	x22 := len(v4)
	v2 = x22
	x32 := make(Audio, v2)
	v3 = x32
	x = x32
	for k := range v3 {
		var v6 = &v3[k]
		var v7 float64
		var v8 float64
		var v9 int
		var v10 int
		var v11 *float64
		var v12 float64
		v10 = k
		v11 = v6
		v9 = k
		x4 := &v5[v9]
		v12 = *x4
		x5 := &v[v10]
		v7 = *x5
		x6 := v12 - v7
		v8 = x6
		*v11 = v8
	}
	return
}
