// Generated by Flux, not meant for human consumption.  Editing may make it unreadable by Flux.

package audio

import (
	"math"
)

func Tanh(x2 Audio) (x Audio) {
	var v Audio
	var v2 Audio
	var v3 Audio
	var v4 int
	v2 = x2
	v3 = x2
	x22 := len(v2)
	v4 = x22
	x3 := make(Audio, v4)
	x = x3
	v = x3
	for k := range v {
		var v5 = &v[k]
		var v6 *float64
		var v7 int
		var v8 float64
		var v9 float64
		v7 = k
		v6 = v5
		x4 := &v3[v7]
		v8 = *x4
		x5 := math.Tanh(v8)
		v9 = x5
		*v6 = v9
	}
	return
}
